# Machine Learning Foundation

## Course 3, Part a: Logistic Regression LAB

## Introduction

We will be using the [Human Activity Recognition with Smartphones](https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) database, which was built from the recordings of study participants who carried a smartphone with an embedded inertial sensor while performing activities of daily living (ADL). The objective is to classify the activities the participants performed into one of the six following categories: walking, walking upstairs, walking downstairs, sitting, standing, and laying.

The following information is provided for each record in the dataset:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration
- Triaxial Angular velocity from the gyroscope
- A 561-feature vector with time and frequency domain variables
- The activity label

More information about the features are available on the website linked above.

In [1]:
!pip install seaborn
!pip install pandas
!pip install numpy
!pip install  matplotlib
!pip install scikit-learn

Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [2]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [3]:
import seaborn as sns, pandas as pd, numpy as np

## Question 1

Import the data and do the following:

* Examine the data types--there are many columns, so it might be wise to use value counts.
* Determine if the floating point values need to be scaled.
* Determine the breakdown of each activity.
* Encode the activity label as an integer.

In [4]:
### BEGIN SOLUTION
data = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML241EN-SkillsNetwork/labs/datasets/Human_Activity_Recognition_Using_Smartphones_Data.csv", sep=',')

The data columns are all floats except for the activity label.

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10299 entries, 0 to 10298
Columns: 562 entries, tBodyAcc-mean()-X to Activity
dtypes: float64(561), object(1)
memory usage: 44.2+ MB

In [6]:
data.describe()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-meanFreq(),fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)"
count,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,...,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000,10299.000000
mean,0.274347,-0.017743,-0.108925,-0.607784,-0.510191,-0.613064,-0.633593,-0.525697,-0.614989,-0.466732,...,0.126708,-0.298592,-0.617700,0.007705,0.002648,0.017683,-0.009219,-0.496522,0.063255,-0.054284
std,0.067628,0.037128,0.053033,0.438694,0.500240,0.403657,0.413333,0.484201,0.399034,0.538707,...,0.245443,0.320199,0.308796,0.336591,0.447364,0.616188,0.484770,0.511158,0.305468,0.268898
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,0.262625,-0.024902,-0.121019,-0.992360,-0.976990,-0.979137,-0.993293,-0.977017,-0.979064,-0.935788,...,-0.019481,-0.536174,-0.841847,-0.124694,-0.287031,-0.493108,-0.389041,-0.817288,0.002151,-0.131880
50%,0.277174,-0.017162,-0.108596,-0.943030,-0.835032,-0.850773,-0.948244,-0.843670,-0.845068,-0.874825,...,0.136245,-0.335160,-0.703402,0.008146,0.007668,0.017192,-0.007186,-0.715631,0.182028,-0.003882
75%,0.288354,-0.010625,-0.097589,-0.250293,-0.057336,-0.278737,-0.302033,-0.087405,-0.288149,-0.014641,...,0.288960,-0.113167,-0.487981,0.149005,0.291490,0.536137,0.365996,-0.521503,0.250790,0.102970
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
data.value_counts()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  tBodyAcc-max()-Y  tBodyAcc-max()-Z  tBodyAcc-min()-X  tBodyAcc-min()-Y  tBodyAcc-min()-Z  tBodyAcc-sma()  tBodyAcc-energy()-X  tBodyAcc-energy()-Y  tBodyAcc-energy()-Z  tBodyAcc-iqr()-X  tBodyAcc-iqr()-Y  tBodyAcc-iqr()-Z  tBodyAcc-entropy()-X  tBodyAcc-entropy()-Y  tBodyAcc-entropy()-Z  tBodyAcc-arCoeff()-X,1  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-X,3  tBodyAcc-arCoeff()-X,4  tBodyAcc-arCoeff()-Y,1  tBodyAcc-arCoeff()-Y,2  tBodyAcc-arCoeff()-Y,3  tBodyAcc-arCoeff()-Y,4  tBodyAcc-arCoeff()-Z,1  tBodyAcc-arCoeff()-Z,2  tBodyAcc-arCoeff()-Z,3  tBodyAcc-arCoeff()-Z,4  tBodyAcc-correlation()-X,Y  tBodyAcc-correlation()-X,Z  tBodyAcc-correlation()-Y,Z  tGravityAcc-mean()-X  tGravityAcc-mean()-Y  tGravityAcc-mean()-Z  tGravityAcc-std()-X  tGravityAcc-std()-Y  tGravityAcc-std()-Z  tGravityAcc-mad()-X  tGravityAcc-mad()-Y  tGravityAcc-mad()-Z  tGravityAcc-max()-X  tGravityAcc-max()-Y  tGravityAcc-max()-Z  tGravityAcc-min()-X  tGravityAcc-min()-Y  tGravityAcc-min()-Z  tGravityAcc-sma()  tGravityAcc-energy()-X  tGravityAcc-energy()-Y  tGravityAcc-energy()-Z  tGravityAcc-iqr()-X  tGravityAcc-iqr()-Y  tGravityAcc-iqr()-Z  tGravityAcc-entropy()-X  tGravityAcc-entropy()-Y  tGravityAcc-entropy()-Z  tGravityAcc-arCoeff()-X,1  tGravityAcc-arCoeff()-X,2  tGravityAcc-arCoeff()-X,3  tGravityAcc-arCoeff()-X,4  tGravityAcc-arCoeff()-Y,1  tGravityAcc-arCoeff()-Y,2  tGravityAcc-arCoeff()-Y,3  tGravityAcc-arCoeff()-Y,4  tGravityAcc-arCoeff()-Z,1  tGravityAcc-arCoeff()-Z,2  tGravityAcc-arCoeff()-Z,3  tGravityAcc-arCoeff()-Z,4  tGravityAcc-correlation()-X,Y  tGravityAcc-correlation()-X,Z  tGravityAcc-correlation()-Y,Z  tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  tBodyAccJerk-mean()-Z  tBodyAccJerk-std()-X  tBodyAccJerk-std()-Y  tBodyAccJerk-std()-Z  tBodyAccJerk-mad()-X  tBodyAccJerk-mad()-Y  tBodyAccJerk-mad()-Z  tBodyAccJerk-max()-X  tBodyAccJerk-max()-Y  tBodyAccJerk-max()-Z  tBodyAccJerk-min()-X  tBodyAccJerk-min()-Y  tBodyAccJerk-min()-Z  tBodyAccJerk-sma()  tBodyAccJerk-energy()-X  tBodyAccJerk-energy()-Y  tBodyAccJerk-energy()-Z  tBodyAccJerk-iqr()-X  tBodyAccJerk-iqr()-Y  tBodyAccJerk-iqr()-Z  tBodyAccJerk-entropy()-X  tBodyAccJerk-entropy()-Y  tBodyAccJerk-entropy()-Z  tBodyAccJerk-arCoeff()-X,1  tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-X,3  tBodyAccJerk-arCoeff()-X,4  tBodyAccJerk-arCoeff()-Y,1  tBodyAccJerk-arCoeff()-Y,2  tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Y,4  tBodyAccJerk-arCoeff()-Z,1  tBodyAccJerk-arCoeff()-Z,2  tBodyAccJerk-arCoeff()-Z,3  tBodyAccJerk-arCoeff()-Z,4  tBodyAccJerk-correlation()-X,Y  tBodyAccJerk-correlation()-X,Z  tBodyAccJerk-correlation()-Y,Z  tBodyGyro-mean()-X  tBodyGyro-mean()-Y  tBodyGyro-mean()-Z  tBodyGyro-std()-X  tBodyGyro-std()-Y  tBodyGyro-std()-Z  tBodyGyro-mad()-X  tBodyGyro-mad()-Y  tBodyGyro-mad()-Z  tBodyGyro-max()-X  tBodyGyro-max()-Y  tBodyGyro-max()-Z  tBodyGyro-min()-X  tBodyGyro-min()-Y  tBodyGyro-min()-Z  tBodyGyro-sma()  tBodyGyro-energy()-X  tBodyGyro-energy()-Y  tBodyGyro-energy()-Z  tBodyGyro-iqr()-X  tBodyGyro-iqr()-Y  tBodyGyro-iqr()-Z  tBodyGyro-entropy()-X  tBodyGyro-entropy()-Y  tBodyGyro-entropy()-Z  tBodyGyro-arCoeff()-X,1  tBodyGyro-arCoeff()-X,2  tBodyGyro-arCoeff()-X,3  tBodyGyro-arCoeff()-X,4  tBodyGyro-arCoeff()-Y,1  tBodyGyro-arCoeff()-Y,2  tBodyGyro-arCoeff()-Y,3  tBodyGyro-arCoeff()-Y,4  tBodyGyro-arCoeff()-Z,1  tBodyGyro-arCoeff()-Z,2  tBodyGyro-arCoeff()-Z,3  tBodyGyro-arCoeff()-Z,4  tBodyGyro-correlation()-X,Y  tBodyGyro-correlation()-X,Z  tBodyGyro-correlation()-Y,Z  tBodyGyroJerk-mean()-X  tBodyGyroJerk-mean()-Y  tBodyGyroJerk-mean()-Z  tBodyGyroJerk-std()-X  tBodyGyroJerk-std()-Y  tBodyGyroJerk-std()-Z  tBodyGyroJerk-mad()-X  tBodyGyroJerk-mad()-Y  tBodyGyroJerk-mad()-Z  tBodyGyroJerk-max()-X  tBodyGyroJerk-max()-Y  tBodyGyroJerk-max()-Z  tBodyGyroJerk-min()-X  tBodyGyroJerk-min()-Y  tBodyGyroJerk-min()-Z  tBodyGyroJerk-sma()  tBodyGyroJerk-energy()-X  tBodyGyroJerk-energy()-Y  tBodyGyroJerk-energy()-Z  tBodyGyroJerk-iqr()-X  tBodyGyroJerk-iqr()-Y  tBodyGyroJerk-iqr()-Z  tBodyGyroJerk-entropy()-X  tBodyGyroJerk-entropy()-Y  tBodyGyroJerk-entropy()-Z  tBodyGyroJerk-arCoeff()-X,1  tBodyGyroJerk-arCoeff()-X,2  tBodyGyroJerk-arCoeff()-X,3  tBodyGyroJerk-arCoeff()-X,4  tBodyGyroJerk-arCoeff()-Y,1  tBodyGyroJerk-arCoeff()-Y,2  tBodyGyroJerk-arCoeff()-Y,3  tBodyGyroJerk-arCoeff()-Y,4  tBodyGyroJerk-arCoeff()-Z,1  tBodyGyroJerk-arCoeff()-Z,2  tBodyGyroJerk-arCoeff()-Z,3  tBodyGyroJerk-arCoeff()-Z,4  tBodyGyroJerk-correlation()-X,Y  tBodyGyroJerk-correlation()-X,Z  tBodyGyroJerk-correlation()-Y,Z  tBodyAccMag-mean()  tBodyAccMag-std()  tBodyAccMag-mad()  tBodyAccMag-max()  tBodyAccMag-min()  tBodyAccMag-sma()  tBodyAccMag-energy()  tBodyAccMag-iqr()  tBodyAccMag-entropy()  tBodyAccMag-arCoeff()1  tBodyAccMag-arCoeff()2  tBodyAccMag-arCoeff()3  tBodyAccMag-arCoeff()4  tGravityAccMag-mean()  tGravityAccMag-std()  tGravityAccMag-mad()  tGravityAccMag-max()  tGravityAccMag-min()  tGravityAccMag-sma()  tGravityAccMag-energy()  tGravityAccMag-iqr()  tGravityAccMag-entropy()  tGravityAccMag-arCoeff()1  tGravityAccMag-arCoeff()2  tGravityAccMag-arCoeff()3  tGravityAccMag-arCoeff()4  tBodyAccJerkMag-mean()  tBodyAccJerkMag-std()  tBodyAccJerkMag-mad()  tBodyAccJerkMag-max()  tBodyAccJerkMag-min()  tBodyAccJerkMag-sma()  tBodyAccJerkMag-energy()  tBodyAccJerkMag-iqr()  tBodyAccJerkMag-entropy()  tBodyAccJerkMag-arCoeff()1  tBodyAccJerkMag-arCoeff()2  tBodyAccJerkMag-arCoeff()3  tBodyAccJerkMag-arCoeff()4  tBodyGyroMag-mean()  tBodyGyroMag-std()  tBodyGyroMag-mad()  tBodyGyroMag-max()  tBodyGyroMag-min()  tBodyGyroMag-sma()  tBodyGyroMag-energy()  tBodyGyroMag-iqr()  tBodyGyroMag-entropy()  tBodyGyroMag-arCoeff()1  tBodyGyroMag-arCoeff()2  tBodyGyroMag-arCoeff()3  tBodyGyroMag-arCoeff()4  tBodyGyroJerkMag-mean()  tBodyGyroJerkMag-std()  tBodyGyroJerkMag-mad()  tBodyGyroJerkMag-max()  tBodyGyroJerkMag-min()  tBodyGyroJerkMag-sma()  tBodyGyroJerkMag-energy()  tBodyGyroJerkMag-iqr()  tBodyGyroJerkMag-entropy()  tBodyGyroJerkMag-arCoeff()1  tBodyGyroJerkMag-arCoeff()2  tBodyGyroJerkMag-arCoeff()3  tBodyGyroJerkMag-arCoeff()4  fBodyAcc-mean()-X  fBodyAcc-mean()-Y  fBodyAcc-mean()-Z  fBodyAcc-std()-X  fBodyAcc-std()-Y  fBodyAcc-std()-Z  fBodyAcc-mad()-X  fBodyAcc-mad()-Y  fBodyAcc-mad()-Z  fBodyAcc-max()-X  fBodyAcc-max()-Y  fBodyAcc-max()-Z  fBodyAcc-min()-X  fBodyAcc-min()-Y  fBodyAcc-min()-Z  fBodyAcc-sma()  fBodyAcc-energy()-X  fBodyAcc-energy()-Y  fBodyAcc-energy()-Z  fBodyAcc-iqr()-X  fBodyAcc-iqr()-Y  fBodyAcc-iqr()-Z  fBodyAcc-entropy()-X  fBodyAcc-entropy()-Y  fBodyAcc-entropy()-Z  fBodyAcc-maxInds-X  fBodyAcc-maxInds-Y  fBodyAcc-maxInds-Z  fBodyAcc-meanFreq()-X  fBodyAcc-meanFreq()-Y  fBodyAcc-meanFreq()-Z  fBodyAcc-skewness()-X  fBodyAcc-kurtosis()-X  fBodyAcc-skewness()-Y  fBodyAcc-kurtosis()-Y  fBodyAcc-skewness()-Z  fBodyAcc-kurtosis()-Z  fBodyAcc-bandsEnergy()-1,8  fBodyAcc-bandsEnergy()-9,16  fBodyAcc-bandsEnergy()-17,24  fBodyAcc-bandsEnergy()-25,32  fBodyAcc-bandsEnergy()-33,40  fBodyAcc-bandsEnergy()-41,48  fBodyAcc-bandsEnergy()-49,56  fBodyAcc-bandsEnergy()-57,64  fBodyAcc-bandsEnergy()-1,16  fBodyAcc-bandsEnergy()-17,32  fBodyAcc-bandsEnergy()-33,48  fBodyAcc-bandsEnergy()-49,64  fBodyAcc-bandsEnergy()-1,24  fBodyAcc-bandsEnergy()-25,48  fBodyAcc-bandsEnergy()-1,8.1  fBodyAcc-bandsEnergy()-9,16.1  fBodyAcc-bandsEnergy()-17,24.1  fBodyAcc-bandsEnergy()-25,32.1  fBodyAcc-bandsEnergy()-33,40.1  fBodyAcc-bandsEnergy()-41,48.1  fBodyAcc-bandsEnergy()-49,56.1  fBodyAcc-bandsEnergy()-57,64.1  fBodyAcc-bandsEnergy()-1,16.1  fBodyAcc-bandsEnergy()-17,32.1  fBodyAcc-bandsEnergy()-33,48.1  fBodyAcc-bandsEnergy()-49,64.1  fBodyAcc-bandsEnergy()-1,24.1  fBodyAcc-bandsEnergy()-25,48.1  fBodyAcc-bandsEnergy()-1,8.2  fBodyAcc-bandsEnergy()-9,16.2  fBodyAcc-bandsEnergy()-17,24.2  fBodyAcc-bandsEnergy()-25,32.2  fBodyAcc-bandsEnergy()-33,40.2  fBodyAcc-bandsEnergy()-41,48.2  fBodyAcc-bandsEnergy()-49,56.2  fBodyAcc-bandsEnergy()-57,64.2  fBodyAcc-bandsEnergy()-1,16.2  fBodyAcc-bandsEnergy()-17,32.2  fBodyAcc-bandsEnergy()-33,48.2  fBodyAcc-bandsEnergy()-49,64.2  fBodyAcc-bandsEnergy()-1,24.2  fBodyAcc-bandsEnergy()-25,48.2  fBodyAccJerk-mean()-X  fBodyAccJerk-mean()-Y  fBodyAccJerk-mean()-Z  fBodyAccJerk-std()-X  fBodyAccJerk-std()-Y  fBodyAccJerk-std()-Z  fBodyAccJerk-mad()-X  fBodyAccJerk-mad()-Y  fBodyAccJerk-mad()-Z  fBodyAccJerk-max()-X  fBodyAccJerk-max()-Y  fBodyAccJerk-max()-Z  fBodyAccJerk-min()-X  fBodyAccJerk-min()-Y  fBodyAccJerk-min()-Z  fBodyAccJerk-sma()  fBodyAccJerk-energy()-X  fBodyAccJerk-energy()-Y  fBodyAccJerk-energy()-Z  fBodyAccJerk-iqr()-X  fBodyAccJerk-iqr()-Y  fBodyAccJerk-iqr()-Z  fBodyAccJerk-entropy()-X  fBodyAccJerk-entropy()-Y  fBodyAccJerk-entropy()-Z  fBodyAccJerk-maxInds-X  fBodyAccJerk-maxInds-Y  fBodyAccJerk-maxInds-Z  fBodyAccJerk-meanFreq()-X  fBodyAccJerk-meanFreq()-Y  fBodyAccJerk-meanFreq()-Z  fBodyAccJerk-skewness()-X  fBodyAccJerk-kurtosis()-X  fBodyAccJerk-skewness()-Y  fBodyAccJerk-kurtosis()-Y  fBodyAccJerk-skewness()-Z  fBodyAccJerk-kurtosis()-Z  fBodyAccJerk-bandsEnergy()-1,8  fBodyAccJerk-bandsEnergy()-9,16  fBodyAccJerk-bandsEnergy()-17,24  fBodyAccJerk-bandsEnergy()-25,32  fBodyAccJerk-bandsEnergy()-33,40  fBodyAccJerk-bandsEnergy()-41,48  fBodyAccJerk-bandsEnergy()-49,56  fBodyAccJerk-bandsEnergy()-57,64  fBodyAccJerk-bandsEnergy()-1,16  fBodyAccJerk-bandsEnergy()-17,32  fBodyAccJerk-bandsEnergy()-33,48  fBodyAccJerk-bandsEnergy()-49,64  fBodyAccJerk-bandsEnergy()-1,24  fBodyAccJerk-bandsEnergy()-25,48  fBodyAccJerk-bandsEnergy()-1,8.1  fBodyAccJerk-bandsEnergy()-9,16.1  fBodyAccJerk-bandsEnergy()-17,24.1  fBodyAccJerk-bandsEnergy()-25,32.1  fBodyAccJerk-bandsEnergy()-33,40.1  fBodyAccJerk-bandsEnergy()-41,48.1  fBodyAccJerk-bandsEnergy()-49,56.1  fBodyAccJerk-bandsEnergy()-57,64.1  fBodyAccJerk-bandsEnergy()-1,16.1  fBodyAccJerk-bandsEnergy()-17,32.1  fBodyAccJerk-bandsEnergy()-33,48.1  fBodyAccJerk-bandsEnergy()-49,64.1  fBodyAccJerk-bandsEnergy()-1,24.1  fBodyAccJerk-bandsEnergy()-25,48.1  fBodyAccJerk-bandsEnergy()-1,8.2  fBodyAccJerk-bandsEnergy()-9,16.2  fBodyAccJerk-bandsEnergy()-17,24.2  fBodyAccJerk-bandsEnergy()-25,32.2  fBodyAccJerk-bandsEnergy()-33,40.2  fBodyAccJerk-bandsEnergy()-41,48.2  fBodyAccJerk-bandsEnergy()-49,56.2  fBodyAccJerk-bandsEnergy()-57,64.2  fBodyAccJerk-bandsEnergy()-1,16.2  fBodyAccJerk-bandsEnergy()-17,32.2  fBodyAccJerk-bandsEnergy()-33,48.2  fBodyAccJerk-bandsEnergy()-49,64.2  fBodyAccJerk-bandsEnergy()-1,24.2  fBodyAccJerk-bandsEnergy()-25,48.2  fBodyGyro-mean()-X  fBodyGyro-mean()-Y  fBodyGyro-mean()-Z  fBodyGyro-std()-X  fBodyGyro-std()-Y  fBodyGyro-std()-Z  fBodyGyro-mad()-X  fBodyGyro-mad()-Y  fBodyGyro-mad()-Z  fBodyGyro-max()-X  fBodyGyro-max()-Y  fBodyGyro-max()-Z  fBodyGyro-min()-X  fBodyGyro-min()-Y  fBodyGyro-min()-Z  fBodyGyro-sma()  fBodyGyro-energy()-X  fBodyGyro-energy()-Y  fBodyGyro-energy()-Z  fBodyGyro-iqr()-X  fBodyGyro-iqr()-Y  fBodyGyro-iqr()-Z  fBodyGyro-entropy()-X  fBodyGyro-entropy()-Y  fBodyGyro-entropy()-Z  fBodyGyro-maxInds-X  fBodyGyro-maxInds-Y  fBodyGyro-maxInds-Z  fBodyGyro-meanFreq()-X  fBodyGyro-meanFreq()-Y  fBodyGyro-meanFreq()-Z  fBodyGyro-skewness()-X  fBodyGyro-kurtosis()-X  fBodyGyro-skewness()-Y  fBodyGyro-kurtosis()-Y  fBodyGyro-skewness()-Z  fBodyGyro-kurtosis()-Z  fBodyGyro-bandsEnergy()-1,8  fBodyGyro-bandsEnergy()-9,16  fBodyGyro-bandsEnergy()-17,24  fBodyGyro-bandsEnergy()-25,32  fBodyGyro-bandsEnergy()-33,40  fBodyGyro-bandsEnergy()-41,48  fBodyGyro-bandsEnergy()-49,56  fBodyGyro-bandsEnergy()-57,64  fBodyGyro-bandsEnergy()-1,16  fBodyGyro-bandsEnergy()-17,32  fBodyGyro-bandsEnergy()-33,48  fBodyGyro-bandsEnergy()-49,64  fBodyGyro-bandsEnergy()-1,24  fBodyGyro-bandsEnergy()-25,48  fBodyGyro-bandsEnergy()-1,8.1  fBodyGyro-bandsEnergy()-9,16.1  fBodyGyro-bandsEnergy()-17,24.1  fBodyGyro-bandsEnergy()-25,32.1  fBodyGyro-bandsEnergy()-33,40.1  fBodyGyro-bandsEnergy()-41,48.1  fBodyGyro-bandsEnergy()-49,56.1  fBodyGyro-bandsEnergy()-57,64.1  fBodyGyro-bandsEnergy()-1,16.1  fBodyGyro-bandsEnergy()-17,32.1  fBodyGyro-bandsEnergy()-33,48.1  fBodyGyro-bandsEnergy()-49,64.1  fBodyGyro-bandsEnergy()-1,24.1  fBodyGyro-bandsEnergy()-25,48.1  fBodyGyro-bandsEnergy()-1,8.2  fBodyGyro-bandsEnergy()-9,16.2  fBodyGyro-bandsEnergy()-17,24.2  fBodyGyro-bandsEnergy()-25,32.2  fBodyGyro-bandsEnergy()-33,40.2  fBodyGyro-bandsEnergy()-41,48.2  fBodyGyro-bandsEnergy()-49,56.2  fBodyGyro-bandsEnergy()-57,64.2  fBodyGyro-bandsEnergy()-1,16.2  fBodyGyro-bandsEnergy()-17,32.2  fBodyGyro-bandsEnergy()-33,48.2  fBodyGyro-bandsEnergy()-49,64.2  fBodyGyro-bandsEnergy()-1,24.2  fBodyGyro-bandsEnergy()-25,48.2  fBodyAccMag-mean()  fBodyAccMag-std()  fBodyAccMag-mad()  fBodyAccMag-max()  fBodyAccMag-min()  fBodyAccMag-sma()  fBodyAccMag-energy()  fBodyAccMag-iqr()  fBodyAccMag-entropy()  fBodyAccMag-maxInds  fBodyAccMag-meanFreq()  fBodyAccMag-skewness()  fBodyAccMag-kurtosis()  fBodyBodyAccJerkMag-mean()  fBodyBodyAccJerkMag-std()  fBodyBodyAccJerkMag-mad()  fBodyBodyAccJerkMag-max()  fBodyBodyAccJerkMag-min()  fBodyBodyAccJerkMag-sma()  fBodyBodyAccJerkMag-energy()  fBodyBodyAccJerkMag-iqr()  fBodyBodyAccJerkMag-entropy()  fBodyBodyAccJerkMag-maxInds  fBodyBodyAccJerkMag-meanFreq()  fBodyBodyAccJerkMag-skewness()  fBodyBodyAccJerkMag-kurtosis()  fBodyBodyGyroMag-mean()  fBodyBodyGyroMag-std()  fBodyBodyGyroMag-mad()  fBodyBodyGyroMag-max()  fBodyBodyGyroMag-min()  fBodyBodyGyroMag-sma()  fBodyBodyGyroMag-energy()  fBodyBodyGyroMag-iqr()  fBodyBodyGyroMag-entropy()  fBodyBodyGyroMag-maxInds  fBodyBodyGyroMag-meanFreq()  fBodyBodyGyroMag-skewness()  fBodyBodyGyroMag-kurtosis()  fBodyBodyGyroJerkMag-mean()  fBodyBodyGyroJerkMag-std()  fBodyBodyGyroJerkMag-mad()  fBodyBodyGyroJerkMag-max()  fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-sma()  fBodyBodyGyroJerkMag-energy()  fBodyBodyGyroJerkMag-iqr()  fBodyBodyGyroJerkMag-entropy()  fBodyBodyGyroJerkMag-maxInds  fBodyBodyGyroJerkMag-meanFreq()  fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  Activity

In [8]:
data.dtypes.value_counts()

float64    561
object       1
Name: count, dtype: int64

In [9]:
data.dtypes.tail()

angle(tBodyGyroJerkMean,gravityMean)    float64
angle(X,gravityMean)                    float64
angle(Y,gravityMean)                    float64
angle(Z,gravityMean)                    float64
Activity                                 object
dtype: object

The data are all scaled from -1 (minimum) to 1.0 (maximum).

In [10]:
data.iloc[:, :-1].min().value_counts()

-1.0    561
Name: count, dtype: int64

In [13]:
data.iloc[:,:-1].min()

tBodyAcc-mean()-X                      -1.0
tBodyAcc-mean()-Y                      -1.0
tBodyAcc-mean()-Z                      -1.0
tBodyAcc-std()-X                       -1.0
tBodyAcc-std()-Y                       -1.0
                                       ...
angle(tBodyGyroMean,gravityMean)       -1.0
angle(tBodyGyroJerkMean,gravityMean)   -1.0
angle(X,gravityMean)                   -1.0
angle(Y,gravityMean)                   -1.0
angle(Z,gravityMean)                   -1.0
Length: 561, dtype: float64

In [15]:
data.iloc[:, :-1].max()

tBodyAcc-mean()-X                       1.0
tBodyAcc-mean()-Y                       1.0
tBodyAcc-mean()-Z                       1.0
tBodyAcc-std()-X                        1.0
tBodyAcc-std()-Y                        1.0
                                       ...
angle(tBodyGyroMean,gravityMean)        1.0
angle(tBodyGyroJerkMean,gravityMean)    1.0
angle(X,gravityMean)                    1.0
angle(Y,gravityMean)                    1.0
angle(Z,gravityMean)                    1.0
Length: 561, dtype: float64

In [16]:
data.iloc[:, :-1].max().value_counts()

1.0    561
Name: count, dtype: int64

Examine the breakdown of activities; they are relatively balanced.

In [17]:
data.Activity.value_counts()

Activity
LAYING                1944
STANDING              1906
SITTING               1777
WALKING               1722
WALKING_UPSTAIRS      1544
WALKING_DOWNSTAIRS    1406
Name: count, dtype: int64

Scikit learn classifiers won't accept a sparse matrix for the prediction column. Thus, either `LabelEncoder` needs to be used to convert the activity labels to integers, or if `DictVectorizer` is used, the resulting matrix must be converted to a non-sparse array.  
Use `LabelEncoder` to fit_transform the "Activity" column, and look at 5 random values.

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Activity'] = le.fit_transform(data.Activity)
data['Activity'].sample(5)
### END SOLUTION

1070    0
8099    4
4544    2
5809    3
183     2
Name: Activity, dtype: int64

## Question 2

* Calculate the correlations between the dependent variables.
* Create a histogram of the correlation values.
* Identify those that are most correlated (either positively or negatively).

In [ ]:
### BEGIN SOLUTION
# Calculate the correlation values
feature_cols = data.columns[:-1]
corr_values = data[feature_cols].corr()

# Simplify by emptying all the data below the diagonal
tril_index = np.tril_indices_from(corr_values)

# Make the unused values NaNs
for coord in zip(*tril_index):
    corr_values.iloc[coord[0], coord[1]] = np.NaN

# Stack the data and convert to a data frame
corr_values = (corr_values
               .stack()
               .to_frame()
               .reset_index()
               .rename(columns={'level_0':'feature1',
                                'level_1':'feature2',
                                0:'correlation'}))

# Get the absolute values for sorting
corr_values['abs_correlation'] = corr_values.correlation.abs()

A histogram of the absolute value correlations.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
sns.set_context('talk')
sns.set_style('white')

ax = corr_values.abs_correlation.hist(bins=50, figsize=(12, 8))
ax.set(xlabel='Absolute Correlation', ylabel='Frequency');

In [ ]:
# The most highly correlated values
corr_values.sort_values('correlation', ascending=False).query('abs_correlation>0.8')
### END SOLUTION

## Question 3

* Split the data into train and test data sets. This can be done using any method, but consider using Scikit-learn's `StratifiedShuffleSplit` to maintain the same ratio of predictor classes.
* Regardless of the method used to split the data, compare the ratio of classes in both the train and test splits.

In [ ]:
### BEGIN SOLUTION
from sklearn.model_selection import StratifiedShuffleSplit

# Get the split indexes
strat_shuf_split = StratifiedShuffleSplit(n_splits=1,
                                          test_size=0.3,
                                          random_state=42)

train_idx, test_idx = next(strat_shuf_split.split(data[feature_cols], data.Activity))

# Create the dataframes
X_train = data.loc[train_idx, feature_cols]
y_train = data.loc[train_idx, 'Activity']

X_test  = data.loc[test_idx, feature_cols]
y_test  = data.loc[test_idx, 'Activity']

In [ ]:
y_train.value_counts(normalize=True)

In [ ]:
y_test.value_counts(normalize=True)
### END SOLUTION

## Question 4

* Fit a logistic regression model without any regularization using all of the features. Be sure to read the documentation about fitting a multi-class model so you understand the coefficient output. Store the model.
* Using cross validation to determine the hyperparameters and fit models using L1 and L2 regularization. Store each of these models as well. Note the limitations on multi-class models, solvers, and regularizations. The regularized models, in particular the L1 model, will probably take a while to fit.

In [ ]:
### BEGIN SOLUTION
from sklearn.linear_model import LogisticRegression

# Standard logistic regression
lr = LogisticRegression(solver='liblinear').fit(X_train, y_train)

In [ ]:
from sklearn.linear_model import LogisticRegressionCV

# L1 regularized logistic regression
lr_l1 = LogisticRegressionCV(Cs=10, cv=4, penalty='l1', solver='liblinear').fit(X_train, y_train)

In [ ]:
# L2 regularized logistic regression
lr_l2 = LogisticRegressionCV(Cs=10, cv=4, penalty='l2', solver='liblinear').fit(X_train, y_train)
### END SOLUTION

## Question 5

* Compare the magnitudes of the coefficients for each of the models. If one-vs-rest fitting was used, each set of coefficients can be plotted separately.

In [ ]:
### BEGIN SOLUTION
# Combine all the coefficients into a dataframe
coefficients = list()

coeff_labels = ['lr', 'l1', 'l2']
coeff_models = [lr, lr_l1, lr_l2]

for lab,mod in zip(coeff_labels, coeff_models):
    coeffs = mod.coef_
    coeff_label = pd.MultiIndex(levels=[[lab], [0,1,2,3,4,5]],
                                 codes=[[0,0,0,0,0,0], [0,1,2,3,4,5]])
    coefficients.append(pd.DataFrame(coeffs.T, columns=coeff_label))

coefficients = pd.concat(coefficients, axis=1)

coefficients.sample(10)

Prepare six separate plots for each of the multi-class coefficients.

In [ ]:
fig, axList = plt.subplots(nrows=3, ncols=2)
axList = axList.flatten()
fig.set_size_inches(10,10)

for ax in enumerate(axList):
    loc = ax[0]
    ax = ax[1]

    data = coefficients.xs(loc, level=1, axis=1)
    data.plot(marker='o', ls='', ms=2.0, ax=ax, legend=False)

    if ax is axList[0]:
        ax.legend(loc=4)

    ax.set(title='Coefficient Set '+str(loc))

plt.tight_layout()
### END SOLUTION

## Question 6

* Predict and store the class for each model.
* Store the probability for the predicted class for each model.

In [ ]:
### BEGIN SOLUTION
# Predict the class and the probability for each
y_pred = list()
y_prob = list()

coeff_labels = ['lr', 'l1', 'l2']
coeff_models = [lr, lr_l1, lr_l2]

for lab,mod in zip(coeff_labels, coeff_models):
    y_pred.append(pd.Series(mod.predict(X_test), name=lab))
    y_prob.append(pd.Series(mod.predict_proba(X_test).max(axis=1), name=lab))

y_pred = pd.concat(y_pred, axis=1)
y_prob = pd.concat(y_prob, axis=1)

y_pred.head()

In [ ]:
y_prob.head()
### END SOLUTION

## Question 7

For each model, calculate the following error metrics:

* Accuracy
* Precision
* Recall
* F-score
* Confusion Matrix

Decide how to combine the multi-class metrics into a single value for each model.

In [ ]:
### BEGIN SOLUTION
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
from sklearn.preprocessing import label_binarize

metrics = list()
cm = dict()

for lab in coeff_labels:

    # Preciision, recall, f-score from the multi-class support function
    precision, recall, fscore, _ = score(y_test, y_pred[lab], average='weighted')

    # The usual way to calculate accuracy
    accuracy = accuracy_score(y_test, y_pred[lab])

    # ROC-AUC scores can be calculated by binarizing the data
    auc = roc_auc_score(label_binarize(y_test, classes=[0,1,2,3,4,5]),
              label_binarize(y_pred[lab], classes=[0,1,2,3,4,5]),
              average='weighted')

    # Last, the confusion matrix
    cm[lab] = confusion_matrix(y_test, y_pred[lab])

    metrics.append(pd.Series({'precision':precision, 'recall':recall,
                              'fscore':fscore, 'accuracy':accuracy,
                              'auc':auc},
                             name=lab))

metrics = pd.concat(metrics, axis=1)

In [ ]:
metrics
### END SOLUTION

## Question 8

* Display or plot the confusion matrix for each model.

In [ ]:
### BEGIN SOLUTION
fig, axList = plt.subplots(nrows=2, ncols=2)
axList = axList.flatten()
fig.set_size_inches(12, 10)

axList[-1].axis('off')

for ax,lab in zip(axList[:-1], coeff_labels):
    sns.heatmap(cm[lab], ax=ax, annot=True, fmt='d');
    ax.set(title=lab);

plt.tight_layout()
### END SOLUTION

---
### Machine Learning Foundation (C) 2020 IBM Corporation